### ISSUE TITLE
Issues with ///

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata-exec#15]
this currently doesn't work
```stata
foreach i in 1 2 ///
    3 {
    di `i'
}
```

**Comment by guanghwang** [comment]
Thanks for this package. I have an idea related to this issue. As stata has its own delimit and commet format, in linux, is it possible to save the selected text/ paragraph to a temporary file and then use the autokey program to send " do "/tmp/SD10054.000000"" to stata so that we could avoid all these format related problems?

Here is a vim plug for stata, which saves the code to a tmp file.
https://github.com/zizhongyan/vim-stata/blob/master/plugin/vim-stata.vim

Best wishes

**Comment by kylebarron** [comment]
First, the original issue is actually resolved as long as you highlight all lines of the code. Then it runs correctly. 

Running code from a temp file would be simple to implement but has a few caveats:
1. Locals don't persist. If you put 
    ```stata
    local test "hello world"
    di "`test'"
    ```
    into a file `tmp.txt` and then run `do tmp.txt`, it'll print the output, but running `di "`test'"` again in the console does nothing. For this reason I wouldn't want running by file to be the default.
2. This would only work when using Stata locally, not on a remote server (since the temporary file would be on your local disk).
3. You wouldn't have a useful command history in Stata. Having the command history in Stata be your actual commands and not just `do "/tmp/SD10054.000000"` is usually more useful.

Back to the original post on this issue, I'd like to enhance the program so that I can have my cursor on the first line and press <kbd>ctrl</kbd>+<kbd>enter</kbd>, and automatically include the next line when it sees `///`. That's a bit more work because that would have to be done in Javascript within Atom.

**Comment by kylebarron** [comment]
The last paragraph is referring to #5 so I'm closing this.
