### ISSUE TITLE
Break execution of current selection if error

### ISSUE THREAD

**Issue by acarril** [kylebarron/stata-exec#31]
When sending a selection to Stata, the execution is not halted even after an error. This is annoying if the succeeding code depends on the one with an error, and potentially dangerous, as errors may slip by. This happens on Windows and Linux. Could it be possible to stop sending commands if Stata outputs an error?

![stata-exec-run](https://user-images.githubusercontent.com/9773292/39074505-af91bd22-44bf-11e8-9a1a-5fa2c714854d.gif)

**Comment by kylebarron** [comment]
Possibly, but it would take some work.

There are two ways to run Stata commands interactively.
- [DoCommand](https://www.stata.com/automation/#runcmds). This runs one command at a time, but returns the Stata return code after each command, so I could check that the return code is 0 before running the next line. First, this has some limitations. You can't use `program define`, `while`, `forvalues`, or `foreach`. And it blocks Stata while the command is running. So in order to run multiple lines from Atom, I'd need to program Atom to keep track of all the lines, wait for a response from Stata after each one, then run the next. Also, this would only work on Windows and Mac.
- [DoCommandAsync](https://www.stata.com/automation/#runcmdsa). This is how I currently send code on Windows on Mac, same as StataEditor and Sublime Stata Enhanced. It doesn't have any of the restrictions listed above, but since all the commands are run asynchronously, there's no way to get the return code of any of the commands.

The most feasible answer is to add a batch execution mode (https://github.com/kylebarron/stata-exec/issues/30). Given the text you select, I could save it to a file and then run that file. Running all the code as a do file would make Stata stop when it encounters an error. But any locals you define in the do file would not be available after it completes. This would work locally on Windows, Mac, and Linux, but not remotely since that would involve saving a file on the remote server.

It really wouldn't take much effort to add that. I just haven't bothered.

**Comment by kylebarron** [comment]
https://github.com/kylebarron/stata-exec/commit/7f6aa5e4108ec62e85457d9fe532ea6cc1b849c9
