### ISSUE TITLE
Run selection can't handle different delimiters or `///` line endings

### ISSUE THREAD

**Issue by nickeubank** [kylebarron/stata-exec#36]
As far as I can tell, while `run dofile` tells stata to open and run a dofile, `run selection` is effectively copy-pasting code into the interactive terminal of stata. This causes issues when code has things that stata doesn't like used interactively, like different delimiters or `///` at the end of lines. 

I think the way sublime text's stata execution package got around this was to copy the selection into a temp file, then pass that temp file's path to stata, telling it to "run this dofile I just made".

How hard would it be to switch the implementation of `run selection` to work that way?

**Comment by kylebarron** [comment]
Can you give example code? I have code that attempts to take out comments.

For example,
```stata
di /// don't run
    "hello world"
```
If I select both lines and do <kbd>ctrl</kbd>+<kbd>enter</kbd> it pastes in Stata
```
di "hello world"

You do have to select both lines though. It currently doesn't have functionality to sense that it needs to include the next line.

**Comment by kylebarron** [comment]
It's true that it can't handle running code with `;` set as the delimiter. I'd like to implement that but it would be a bit of work

**Comment by nickeubank** [comment]
Yeah, I use `;` and `///` a lot for things like plots. Things like:

```
 twoway (scatter mpg price) /// 
               (scatter weight price), /// 
               legend(off) ///
               title("prices!")
```

Doesn't have to be a priority if not urgent.

**Comment by nickeubank** [comment]
Oh shoot -- it *is* only `;` that's causing me problems! so sorry -- I use both, and thought they were both having issues... apparently I mis-read my errors!

**Comment by kylebarron** [comment]
Yeah it's just `;`. I've wanted to do that for a while, see #6. It might be easiest to solve this by running batch scripts, see #30, but then you'd need a `#delimit ;` command that starts every dofile sent. I also don't care personally about batch scripts since I do all my work on remote servers and sending batch scripts as "do this local file" doesn't work in that way.

If I created a way to concatenate commands when using the `;` delimiter, the best way to do it would be to search upwards in the file in Atom and see if `#delimit ;` appears and if it exists after any `#delimit cr` statements. But I'd probably stipulate a restriction that a given selection can't contain _both_ carriage return-delimited lines and `;`-delimited lines. That would simplify things a lot.

**Comment by nickeubank** [comment]
Another option is to just treat `;` like `\\\` when running selections...

**Comment by kylebarron** [comment]
Those have opposite meanings... `;` means end a command; `///` means the next line is part of the same command

**Comment by kylebarron** [comment]
You should be able to use this with `Run Batch` now

**Comment by nickeubank** [comment]
Yay!!! Thanks!

**Comment by kylebarron** [comment]
@nickeubank You can also program interactively with `;` line endings in the new Stata Jupyter Kernel.
https://github.com/kylebarron/stata_kernel/
https://kylebarron.github.io/stata_kernel/
![image](https://user-images.githubusercontent.com/15164633/44423538-52376c80-a554-11e8-875c-73291608148e.png)
![image](https://user-images.githubusercontent.com/15164633/44423564-62e7e280-a554-11e8-9dfc-4a043d6e624e.png)

**Comment by nickeubank** [comment]
Even better! You're the best. Thanks @kylebarron

**Comment by kylebarron** [comment]
@mcaceresb helped a ton as well!
