### ISSUE TITLE
Batch execution mode bugs?

### ISSUE THREAD

**Issue by wschpero** [kylebarron/stata-exec#41]
Hey @kylebarron,

Thanks for adding in a batch execution mode in v1.7! Unfortunately, I’m encountering two separate errors when using it on MacOS 10.13.6 with Stata 14.2, both of which are evident if you run the example below.

```
sysuse auto
local covlist "price mpg rep78 headroom"
foreach cov in `covlist' {
	replace `cov'=`cov'*100
}
```

1. The batch execution will drop the closing bracket if you don’t include additional text below it in the selection.

2. It seems like stata-exec is adding characters (specifically, backslashes) to any strings passed through.

Thanks again for maintaining this great package. Just an FYI re the above.

Best,
Will

**Comment by kylebarron** [comment]
I'll push a new release out tomorrow or Monday. I think both of those issues should be solved.

**Comment by wschpero** [comment]
Thanks! String pass-through is fixed, but I'm still finding that the last line of code is dropped.

**Comment by kylebarron** [comment]
That's weird because it works for me.
<img width="186" alt="image" src="https://user-images.githubusercontent.com/15164633/43403682-b4becb50-93e3-11e8-94ff-f9868f9a6680.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/15164633/43403712-d095254a-93e3-11e8-8b8b-d2ac4a27fc72.png">

Can you try 
```
apm uninstall stata-exec
apm install kylebarron/stata-exec
```
and see if it works? I want you to test the two newest commits.

**Comment by wschpero** [comment]
Seems fine now!

**Comment by kylebarron** [comment]
Great. You should do 
```
apm uninstall stata-exec
apm install stata-exec
```
because I think that you won't be notified of updates when you have the Git version installed.

**Comment by wschpero** [comment]
Will do. Many thanks!
